CREATE TABLE Entity0 (
 Attribute0 CHAR(10) NOT NULL
);

ALTER TABLE Entity0 ADD CONSTRAINT PK_Entity0 PRIMARY KEY (Attribute0);


CREATE TABLE User (
 USER ID INT NOT NULL,
 Name VARCHAR(100) NOT NULL,
 Surname VARCHAR(100),
 Email VARCHAR(100),
 RegistrationDate DATE,
 HomeAddress CHAR(10),
 HashedPassword VARCHAR(255)
);

ALTER TABLE User ADD CONSTRAINT PK_User PRIMARY KEY (USER ID);


CREATE TABLE Entity3 (
 USER ID INT NOT NULL
);

ALTER TABLE Entity3 ADD CONSTRAINT PK_Entity3 PRIMARY KEY (USER ID);


CREATE TABLE Meeting (
 USER ID INT NOT NULL,
 MEETING ID INT NOT NULL,
 Name CHAR(10),
 StartingDate DATE,
 Duration INT,
 Location VARCHAR(10)
);

ALTER TABLE Meeting ADD CONSTRAINT PK_Meeting PRIMARY KEY (USER ID,MEETING ID);


CREATE TABLE Preferences (
 USER ID INT NOT NULL,
 MinimizeCarbonFootprint CHAR(10),
 MaxWalkingDistance CHAR(10),
 MaxCyclingDistance CHAR(10),
 NoPublicTransportationsAfter CHAR(10),
 AvoidTolls CHAR(10),
 AvoidMotorways CHAR(10)
);

ALTER TABLE Preferences ADD CONSTRAINT PK_Preferences PRIMARY KEY (USER ID);


CREATE TABLE Reminder (
 USER ID INT NOT NULL,
 MEETING ID INT NOT NULL,
 Time TIME(10)
);

ALTER TABLE Reminder ADD CONSTRAINT PK_Reminder PRIMARY KEY (USER ID,MEETING ID);


CREATE TABLE TravelMean (
 USER ID INT NOT NULL,
 Name CHAR(10),
 Selected BIT(10)
);

ALTER TABLE TravelMean ADD CONSTRAINT PK_TravelMean PRIMARY KEY (USER ID);


CREATE TABLE Break (
 USER ID INT NOT NULL,
 Name CHAR(10),
 StartingTime TIME(10),
 Duration INT,
 Recurrent BIT(10),
 Lunch BIT(10),
 DayOfWeek CHAR(10)
);

ALTER TABLE Break ADD CONSTRAINT PK_Break PRIMARY KEY (USER ID);


ALTER TABLE Entity3 ADD CONSTRAINT FK_Entity3_0 FOREIGN KEY (USER ID) REFERENCES User (USER ID);


ALTER TABLE Meeting ADD CONSTRAINT FK_Meeting_0 FOREIGN KEY (USER ID) REFERENCES User (USER ID);


ALTER TABLE Preferences ADD CONSTRAINT FK_Preferences_0 FOREIGN KEY (USER ID) REFERENCES User (USER ID);


ALTER TABLE Reminder ADD CONSTRAINT FK_Reminder_0 FOREIGN KEY (USER ID,MEETING ID) REFERENCES Meeting (USER ID,MEETING ID);


ALTER TABLE TravelMean ADD CONSTRAINT FK_TravelMean_0 FOREIGN KEY (USER ID) REFERENCES Preferences (USER ID);


ALTER TABLE Break ADD CONSTRAINT FK_Break_0 FOREIGN KEY (USER ID) REFERENCES Preferences (USER ID);


